/*
 * borderFrmWin.java
 *
 * Created on __DATE__, __TIME__
 */

package com.attilax.xml;

import java.awt.Color;
import java.awt.Container;

import javax.swing.BorderFactory;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.SpringLayout;

/**
 *  
 * @author  __USER__
 */
public class borderFrmWin extends javax.swing.JFrame {

	/** Creates new form borderFrmWin */
	public borderFrmWin() {
		this.setUndecorated(true);
		initComponents();
		Container contentPane = this.getContentPane();
		((JPanel) contentPane).setOpaque(false);//jeig must yeu in customed broder mode
		JLayeredPane layeredPane = this.getLayeredPane();
		this.getRootPane().setBorder(
				BorderFactory.createLineBorder(new Color(48, 187, 227), 1));
		layeredPane.setBorder(BorderFactory.createLineBorder(Color.black, 1));
		jPanel2out.setBorder(BorderFactory.createLineBorder(new Color(48, 187,
				227), 1));

		jPanel2_in.setBorder(BorderFactory.createLineBorder(Color.black, 1));
		jPanel2out.setBounds(this.getContentPane().getBounds());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jPanel2out = new javax.swing.JPanel();
		jPanel2_in = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("title......................................................................title........................................................");

		jPanel2out.setBackground(new java.awt.Color(153, 153, 153));

		javax.swing.GroupLayout jPanel2_inLayout = new javax.swing.GroupLayout(
				jPanel2_in);
		jPanel2_in.setLayout(jPanel2_inLayout);
		jPanel2_inLayout.setHorizontalGroup(jPanel2_inLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 431, Short.MAX_VALUE));
		jPanel2_inLayout.setVerticalGroup(jPanel2_inLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 206,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel2outLayout = new javax.swing.GroupLayout(
				jPanel2out);
		jPanel2out.setLayout(jPanel2outLayout);
		jPanel2outLayout.setHorizontalGroup(jPanel2outLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2_in,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel2outLayout.setVerticalGroup(jPanel2outLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2outLayout
						.createSequentialGroup()
						.addGap(1, 1, 1)
						.addComponent(jPanel2_in,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(32, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addComponent(jLabel1)
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addGap(1, 1, 1)
								.addComponent(jPanel2out,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jLabel1)
						.addGap(1, 1, 1)
						.addComponent(jPanel2out,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new borderFrmWin().setVisible(true);
			}
		});
		System.out.println(Integer.MAX_VALUE);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel2_in;
	private javax.swing.JPanel jPanel2out;
	// End of variables declaration//GEN-END:variables

}